apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
data:
  username: YWRtaW4=  # admin in base64
  password: c2VjcmV0cGFzc3dvcmQ=  # secretpassword in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todo-app
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnNlY3JldHBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvdG9kb2xpc3Q/YXV0aFNvdXJjZT1hZG1pbg==  # mongodb://admin:secretpassword@mongodb:27017/todolist?authSource=admin in base64